In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
x=np.arange(1,25).reshape(12,2)
y=np.array([0,1,1,0,1,0,0,1,1,0,1,0])
print(x)
print(y)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[0 1 1 0 1 0 0 1 1 0 1 0]


In [2]:
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train)

[[ 5  6]
 [ 3  4]
 [ 9 10]
 [19 20]
 [11 12]
 [17 18]
 [ 7  8]
 [21 22]
 [15 16]]


In [3]:
print(x_test)

[[ 1  2]
 [23 24]
 [13 14]]


In [4]:
print(y_train)
print(y_test)

[1 1 1 0 0 1 0 1 1]
[0 0 0]


In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=4,random_state=4,shuffle=False)

In [6]:
print(x_train)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [7]:
print(x_test)

[[17 18]
 [19 20]
 [21 22]
 [23 24]]


In [8]:
print(y_train)
print(y_test)

[0 1 1 0 1 0 0 1]
[1 0 1 0]
