In [1]:
import numpy as np
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [2]:
a.shape

(20,)

In [3]:
a[4]

4

In [7]:
a=np.arange(18).reshape(3,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [9]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
np.linspace(0,10,num=3)

array([ 0.,  5., 10.])

In [13]:
print(a.ndim)

2


In [15]:
a=np.array(22)
print(a)

22


In [16]:
a=np.array([1,2,3,4,5])
x=a.view()
a[0]=42
print(a)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [17]:
a=np.array([1,2,3,4,5])
x=a.copy()
a[0]=42
print(a)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [20]:
np.diag(a)

array([[42,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  5]])

In [21]:
np.random.random([2,3])

array([[0.92492306, 0.76222499, 0.56975394],
       [0.52095259, 0.74446936, 0.82007471]])

In [24]:
a=np.array([1,2,3,4,5,6])
print(a[1:5])

[2 3 4 5]


In [25]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.concatenate([a,b])
print(x)

[1 2 3 4 5 6]
